import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { usePathname } from "next/navigation";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // This is a workaround for Next.js app router: usePathname only works in client components.
  // So, we check for the theme provider in all pages except home and login.
  // We'll use a simple check on window.location.pathname for now.
  let isHomeOrLogin = false;
  if (typeof window !== "undefined") {
    const path = window.location.pathname;
    isHomeOrLogin = path === "/" || path.startsWith("/login");
  }
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {isHomeOrLogin ? (
          children
        ) : (
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            {children}
          </ThemeProvider>
        )}
      </body>
    </html>
  );
}
